### ISSUE TITLE
Navigation Backcolor ?

### ISSUE THREAD

**Issue by tonyfonager** [scriptBoris/NavigationSam#1]
I have now implemented your fine Nuget package for my Xamarin.Forms app.

Normaly my NavigationPage background color is set via a style definition :

```
<Color x:Key="NavigationBarColor">#6d4585</Color>

<Style TargetType="NavigationPage">
	<Setter Property="BarBackgroundColor" Value="{StaticResource NavigationBarColor}" />
	<Setter Property="BarTextColor" Value="{StaticResource NavigationBarTextColor}" />
</Style>
```

But when I change to using your NavigationPageSam(), it becomes white ?

Any idea how I can change the color in my app now ?

**Comment by scriptBoris** [comment]
@tonyfonager let me try to reproduce the problem and find a solution. I'll do it: right now

**Comment by tonyfonager** [comment]
Great, I have looked thru your source to see if I could find something that did it, but without luck.

So it could be something in my code, maybe ... I dont know!

But I have temporarily fix it by overriding your class and setting it implicit like this :

```
public partial class NavigationPageQuizmo : NavigationPageSam
{
	public NavigationPageQuizmo(Page root) : base(root)
	{
		this.BarBackgroundColor = Color.FromHex("#6d4585");
		this.BarTextColor = Color.White;
	}
}
```

It fixes it for now, and I can start testing your nice package ;-)

**Comment by tonyfonager** [comment]
> Can you send me a more detailed code?

Its part of a huge / complex game project, so it would be too much of a hassle to separate it out, sorry!

But feel free to ask me anything, and I will provide it - as I wrote initially, the background color of my navigation area was set thru a style inside app.xaml page, but when I added your control that area became white (default) again.

**Comment by scriptBoris** [comment]
https://github.com/scriptBoris/NavigationSam/tree/issue1%23navigationBackcolor
This branch for solve you problem (in process)

**Comment by tonyfonager** [comment]
Sweet, I also wondered why that constructor with no parameter was missing 👍 

You gonna push a new package later ?

And thanks for the quick reply @scriptBoris

**Comment by scriptBoris** [comment]
I can publish new version on right now, if i solve problem

**Comment by scriptBoris** [comment]
@tonyfonager Try to specify the type explicitly 
![image](https://user-images.githubusercontent.com/29772096/107155337-caa77780-69b2-11eb-80ce-d63005bde824.png)

**Comment by tonyfonager** [comment]
When I try adding that, I do not get any classes from intellisense when typing "navSam:"

![image](https://user-images.githubusercontent.com/837894/107155810-c19ab400-697a-11eb-80b1-bea2fbcea207.png)

I tried adding it manually, could compile but navigation area is still white.

Please note, I have not update Nuget or anything!

**Comment by scriptBoris** [comment]
@tonyfonager the problem is most likely due to the fact that NavigationPageSam does not have a open constructor. I will fix this in the new version of the package 1.0.2

BUT, you can now solve this problem. 
Just write {Type navSam:NavigationPageSam}

It worked

**Comment by tonyfonager** [comment]
I tried adding it anyway, with no luck.

But let me was and test the new Nuget 1.0.2

**Comment by scriptBoris** [comment]
> I tried adding it anyway, with no luck.
> 
> But let me was and test the new Nuget 1.0.2

Nuget 1.0.2 is published

**Comment by tonyfonager** [comment]
Thanks alot, I have upgraded to 1.0.2 and can confirm it works now 🥇

**Comment by scriptBoris** [comment]
@tonyfonager cool!

**Comment by tonyfonager** [comment]
Starred 👍

**Comment by rykase5566** [comment]
Same issue..
But can I change color of Arrow Icon?
(My title's background color is #fbfcfe, who is almost white)
