### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by FS-FIT** [scriptBoris/NavigationSam#10]
Hello Boris,

Thank you very much for your excellent work. I have just tried to integrate the functionality into my project. It looks like I will get a second navigation bar without functionality after the integration and the RequestPop will not fired. have you any hint?

many thanks

**Comment by scriptBoris** [comment]
@FS-FIT hello, can you send me Sample project here? I try help with integration

**Comment by FS-FIT** [comment]
Hi Boris,
sorry fo my delay. I had to clean up the project first. Thanks for your help :-) Can you please delete the zip file after download?

**Comment by scriptBoris** [comment]
@FS-FIT yeah sure

**Comment by scriptBoris** [comment]
@FS-FIT i know you problem.

You used next schema:
```
root NavigationPage
=> MasterDetailPage
=> => NavigationPage
=> => => {Pages from folder Views}
```
In total, we have the result: 
- root NavigationPage draw Navigation bar
- NavigationPage that is at the MasterDetailPage (Detail) draw Navigation bar

To solve your problem, you must stop using navigation in App.xaml.cs:76 code line. And using NavigationPageSam for any childrens MasterDetailPage

**Comment by FS-FIT** [comment]
Thank you very much for your help. I have cleaned up the code and removed unnecessary dependencies in the navigation. The next ten cups of coffee are on me, enjoy!

**Comment by scriptBoris** [comment]
@FS-FIT no problem, thank you sir!

**Comment by FS-FIT** [comment]
I have one more more integration question: is it possible to handle the android navigation back hardware button with navigationsam?
