### ISSUE TITLE
iOS 12.4 causes back button to disappear upon ReqestPop Cancel

### ISSUE THREAD

**Issue by brianjohnson62** [scriptBoris/NavigationSam#3]
Everything is working fine except on iPhone 7 iOS 12.4 (and at least 1 earlier iOS version I tried). When you make a change on the Sample Code Edit page and hit cancel, the Pop is cancelled but the back button arrow disappears. Then there is no way to get back. This happens in my App as well as in your Sample Code. Everything works fine on iOS 14.4.

**Comment by scriptBoris** [comment]
> Everything is working fine except on iPhone 7 iOS 12.4 (and at least 1 earlier iOS version I tried). When you make a change on the Sample Code Edit page and hit cancel, the Pop is cancelled but the back button arrow disappears. Then there is no way to get back. This happens in my App as well as in your Sample Code. Everything works fine on iOS 14.4.

Me need more time. 1-2 days maybe. Tip me, can be create iPhone simulator with iOS 12.4 on MacOS?
I have iPhone 7 (iOS 14.4). Apple forbid downgrade OS on they devices, assholes.

**Comment by brianjohnson62** [comment]
I detected it on an actual device but was I was able to reproduce with the Simulator.

 

In XCode->Preferences Components tab, install iOS 12.4 Simulator.

 

Then in Simulator, you can create a new Sim with File->new Iphone 7, OS version 12.4.

 

 

Again, thanks for the quick reply.

**Comment by scriptBoris** [comment]
@brianjohnson62 good news, i solve the problem. I coming soon publish new version nuget package

**Comment by scriptBoris** [comment]
@brianjohnson62 nuget 1.0.4 is now available (and i write you e-mail, check please)

**Comment by scriptBoris** [comment]
@brianjohnson62 check nuget 1.0.5 =)

**Comment by brianjohnson62** [comment]
Ah. I experienced that and ended up implementing INavigationPopInterceptor on all views. I will try 1.0.5, and back out those changes. Thanks.

**Comment by scriptBoris** [comment]
@brianjohnson62 please tell me, what problems do you have with NavigationSam?

**Comment by brianjohnson62** [comment]
I will . So far all is good. Thanks.
