### ISSUE TITLE
Navigation Arrow Icon

### ISSUE THREAD

**Issue by rykase5566** [scriptBoris/NavigationSam#4]
I have a issue as the same as [this post](https://github.com/scriptBoris/NavigationSam/issues/1).
I can change background color now, thank a lot.

But I have another question about arrow Icon in Android view.
The background color of my title is white, and it cause the arrow Icon is invisible.

![image](https://user-images.githubusercontent.com/55685550/111445415-58128000-8746-11eb-828f-12df0d98f170.png)
(My Android View)

Can I change the color of arrow icon?
(I am newbie for Xamarin)

**Comment by scriptBoris** [comment]
@rykase5566 hello, as far as I know this is a problem a native Navigation Xamarin.Forms. Give me time, I'll try to change the color of the arrow

**Comment by rykase5566** [comment]
Thanks for the reply! 
I resolved it
I edit BarTextColor and it work!

**Comment by scriptBoris** [comment]
@rykase5566 nice, close the issue?

**Comment by rykase5566** [comment]
i starred, thanks a lot
