### ISSUE TITLE
On Drawer page not calling Messenger.Default and pop up some issues

### ISSUE THREAD

**Issue by Polyariz** [scriptBoris/NavigationSam#5]
If you open any page where implemented INavigationPopInterceptor and then go back to main page of MasterDetailPage, won't be work await Detail.Navigation.PushAsync((Page)Activator.CreateInstance(typeof(MyPage)), false); or 
 await Detail.Navigation.PushAsync(new MyPage(), false);

**Comment by scriptBoris** [comment]
Hello Polyariz, need source code for reproduce the problem. Can you?

**Comment by Polyariz** [comment]
Hello Boris! Sorry for delay with response.
There is the repository to test the bug: https://github.com/Polyariz/TestNavigationSam

Reproduce the issue:
1) Open drawer page->click "BugTest" to open the page.
2) Go Back to Home Page -> Click  NavSamTest Button
3) Try again open BugTest Page. This page will not be openning.
Or these steps :
2) and then 3)

**Comment by scriptBoris** [comment]
@Polyariz thanks, I will solve your problem soon

**Comment by scriptBoris** [comment]
@Polyariz i see you project, but class Messenger - is not found

**Comment by scriptBoris** [comment]
Apparently, the problem could not be solved :(
