### ISSUE TITLE
Gray Line Below Tool Bar

### ISSUE THREAD

**Issue by tmn9491** [scriptBoris/NavigationSam#6]
Hi, 

I am using your control version 1.0.6 in my app and noticed that there is a gray line between the tool bar and my main screen as in the attached screenshot on iOS. Could you let me know how to remove it?

It also appears on your GitHub visual examples here:
https://github.com/scriptBoris/NavigationSam/blob/master/Nuget/2.gif

<img width="405" alt="Screen Shot 2021-04-27 at 16 22 57" src="https://user-images.githubusercontent.com/61121387/116314634-fa297d00-a774-11eb-8b8e-426568f4a830.png">

**Comment by scriptBoris** [comment]
It is configurable just like native NavigationPage. Such as:

<Application 
             xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
             xmlns:navSam="clr-namespace:NavigationSam;assembly=NavigationSam"
             xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core"
             x:Class="Test.App">
    <Application.Resources>
        <ResourceDictionary>


            <Style TargetType="{Type navSam:NavigationPageSam}">
                <Setter Property="BarBackgroundColor" Value="White" />
                <Setter Property="BarTextColor" Value="Black" />
                
                
                <Setter Property="ios:NavigationPage.HideNavigationBarSeparator" Value="True"/>
            </Style>

        </ResourceDictionary>
    </Application.Resources>
</Application>

**Comment by tmn9491** [comment]
Thanks for the reply, but this does not seem to work for me.

**Comment by scriptBoris** [comment]
> Thanks for the reply, but this does not seem to work for me.

Give me sample project, please

**Comment by tmn9491** [comment]
I tried with your sample project and it worked. It must be something with my project then. Thanks.

**Comment by scriptBoris** [comment]
@tmn9491 can you write here when solve problem?

**Comment by tmn9491** [comment]
I updated Xamarin Forms to the latest version and it seemed to have solved the issue. However, once I switch the device theme, the navigation bar separator came back. I still have no solution to fix it.

The problem is described in the below link.
https://github.com/xamarin/Xamarin.Forms/issues/10578
