### ISSUE TITLE
Crash on Device: System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by oac28x** [scriptBoris/NavigationSam#9]
iPad 6th Gen running iPadOS 13.3, It does not fail on simulator of iPad 6th Gen running iOS 12.4.

Crashin on:

protected virtual bool OnDidPush(UINavigationBar navigationBar, UINavigationItem item)
{
    if(IsIosOver14)
         return true;
    
    if(navigationBar.Items.Lenght > 1)
    {
         var view = navigationBar.Subviews[2].Subviews.FirstOrDefault();    //Crashing Line
         ...

CrashReport:

NavigationSamRenderer.OnDidPushItem (UIKit.UINavigationBar navigationBar, UIKit.UINavigationItem item) C:\Users\Scriptboris\source\repos\NavigationSam\Lib\NavigationSam.iOS\NavigationSamRenderer.cs:68

NavigationSamRenderer.DidPushItem (UIKit.UINavigationBar navigationBar, UIKit.UINavigationItem item) C:\Users\Scriptboris\source\repos\NavigationSam\Lib\NavigationSam.iOS\NavigationSamRenderer.cs:41

(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:86

UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:65
Application.Main (System.String[] args) /Users/AppName/iOS/Main.cs:17

**Comment by scriptBoris** [comment]
Thanks for your bug report, please wait some time

**Comment by scriptBoris** [comment]
@oac28x how i can create emulator iPad 6gen on iPadOS 13.3?
![image](https://user-images.githubusercontent.com/29772096/134735629-04aa0379-d902-4345-8a82-0a6e8b2bd247.png)
This only iOS, tvOS, watchOS

**Comment by GioAbq** [comment]
It's about iOS 13.3. @oac28x misspelled OS name

**Comment by scriptBoris** [comment]
@Janek91 OK, i will check this problem, wait for...
